modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="peculiarpooch" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Peculiar Pooch" #mandatory
credits="VakyPanda" #optional
authors="Coda" #optional
description='''This mod adds borzoi dogs to the game!'''